/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/layout/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    CtaSection: typeof import('./src/components/landing/CtaSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/landing/HeroSection.vue')['default']
    ProblemSection: typeof import('./src/components/landing/ProblemSection.vue')['default']
    ProcessSection: typeof import('./src/components/landing/ProcessSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./src/components/landing/ServicesSection.vue')['default']
    SolutionSection: typeof import('./src/components/landing/SolutionSection.vue')['default']
    TargetAudienceSection: typeof import('./src/components/landing/TargetAudienceSection.vue')['default']
    WhyUsSection: typeof import('./src/components/landing/WhyUsSection.vue')['default']
  }
}
